name       : vmpk
version    : 0.7.1
release    : 1
source     :
    - https://downloads.sourceforge.net/project/vmpk/vmpk/0.7.1/vmpk-0.7.1.tar.gz : 4afe1ad486c7463df95f5697dfb3551cfbbda22c8b89561832f37011101af2a6
license    : GPL-3.0-only
component  : multimedia.audio
summary    : Virtual MIDI Piano Keyboard
description: |
    Virtual MIDI Piano Keyboard is a MIDI events generator and receiver. It doesn't produce any sound by itself, but can be used to drive a MIDI synthesizer (either hardware or software, internal or external). You can use the computer's keyboard to play MIDI notes, and also the mouse. You can use the Virtual MIDI Piano Keyboard to display the played MIDI notes from another instrument or MIDI file player. To do so, connect the other MIDI port to the input port of VMPK.
builddeps  :
    - pkgconfig(drumstick-rt)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
rundeps  :
    - drumstick
    - qt5-x11extras
build      : |
    %cmake .
    %make
install    : |
    %make_install
