name       : vmpk
version    : 0.8.9
release    : 6
source     :
    - https://downloads.sourceforge.net/project/vmpk/vmpk/0.8.9/vmpk-0.8.9.tar.bz2 : 5c5452b4fa0f66d18d796c0d8f6acdfdbb02d4f00b219d451e013c5e6e7b232c
homepage   : https://vmpk.sourceforge.io
license    : GPL-3.0-only
component  : multimedia.audio
summary    : Virtual MIDI Piano Keyboard
description: |
    Virtual MIDI Piano Keyboard is a MIDI events generator and receiver. It doesn't produce any sound by itself, but can be used to drive a MIDI synthesizer (either hardware or software, internal or external). You can use the computer's keyboard to play MIDI notes, and also the mouse. You can use the Virtual MIDI Piano Keyboard to display the played MIDI notes from another instrument or MIDI file player. To do so, connect the other MIDI port to the input port of VMPK.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(drumstick-rt)
    - docbook-xml
setup      : |
    %cmake_ninja 
build      : |
    %ninja_build
install    : |
    %ninja_install
